### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by amilajack** [arei/Threadful#2]

**Comment by arei** [comment]
I suppose it depends on your definition of "alive".

Honestly, I had no idea anyone even used it at all. Was super excited to hear that you are using it when you sent the PR. :smiley: 

However, from a maintenance point of view maintaining this project is not currently a priority for me nor do I see that changing in the future.  I have other OS efforts that require my attention more than this one not to mention my full time job. So in that respect, not all that alive.

That said, I have noted your pull request and will get it merged in at some point.

**Comment by amilajack** [comment]
I am willing to offer long term and active support for this project if that is fine with you.

I'm considering:
- Refactoring
- Offering test coverage
- Providing support for modern node versions
- Improving performance

**Comment by arei** [comment]
I have given you collaboration permissions.  Go to town.  Let me know if you have questions.

**Comment by amilajack** [comment]
@arei thanks!
